version: '3.8'

services:
  api:
    container_name: api
    image: api:ws
    build: 
      context: api
    ports:
      - 8000:8000
    networks:
      - webshell
    volumes:
      - ./api:/home/python/app
    env_file:
      - .env
    restart: always

  ui:
    container_name: ui
    image: ui:ws
    build: 
      context: ui
    ports:
      - 4000:4000
    networks:
      - webshell
    volumes:
      - ./ui:/home/node/app
    env_file:
      - .env
    depends_on:
      - api
    restart: always

networks:
  webshell:
    name: webshell
    driver: bridge
